### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by hellojaccc** [tripupapp/tripup-ios#4]
**Describe the bug**

App crashes when i click something

**To Reproduce**

Click anything like photos, setting options

**Expected behavior**
Show contents

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14.6
 - Browser: [e.g. stock browser, safari, firefox]
 - App Version: 2.1.1

**Additional context**

https://www.icloud.com/iclouddrive/0Ac-QPcqV0YP7gncvbKnBPIzg#swiftybeaver

**Comment by vin047** [comment]
I believe this issue was fixed with the latest release, App Store version [2.1.2](https://www.reddit.com/r/tripup/comments/p4vpkg/212_release_library_backup_improvements), build no [1.1.2.17](https://github.com/tripupapp/tripup-ios/releases/tag/1.1.2.17). @hellojaccc let me know if you're still experiencing this issue after updating the app – if so, I will re-open it 🙂
